(define (domain adl-forall-precondition)
  (:requirements :strips :typing :action-costs)
  (:types item)
  (:predicates (clean ?i - item) (done))
  (:functions (cost))
  (:action clean-item :parameters (?i - item)
    :precondition () :effect (and (clean ?i) (increase (cost) 1)))
  (:action finish :parameters ()
    :precondition (forall (?i - item) (clean ?i))
    :effect (and (done) (increase (cost) 1))))
