(define (problem BLOCKS-8-0)
  (:domain BLOCKS)
  (:objects A B C D E F G H)
  (:init
    (ONTABLE A)
    (ON F A)
    (ON C F)
    (CLEAR C)
    (ONTABLE B)
    (ON G B)
    (CLEAR G)
    (ONTABLE D)
    (ON H D)
    (CLEAR H)
    (ONTABLE E)
    (CLEAR E)
    (HANDEMPTY))
  (:goal
    (AND
      (ON B G)
      (ON G E)
      (ON E A)
      (ON A H)
      (ON H C)
      (ON C F)
      (ON F D)))
)
