(define (domain adl-forall-effect)
  (:requirements :strips :typing :conditional-effects :action-costs)
  (:types item)
  (:predicates (marked ?i - item))
  (:functions (cost))
  (:action mark-all :parameters ()
    :precondition ()
    :effect (and (forall (?i - item) (marked ?i)) (increase (cost) 1)))
  (:action mark-one :parameters (?i - item)
    :precondition ()
    :effect (and (marked ?i) (increase (cost) 4))))
