[package]
name = "planforge-translate"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
description = "Translation and preprocessing of PDDL planning tasks into PlanForge's SAS+ representation."
repository = "https://github.com/mrlab-ai/PlanForge"
readme = "../README.md"
keywords = ["planning", "pddl", "sas-plus", "translator"]
categories = ["science", "algorithms", "parser-implementations"]
license = "LGPL-3.0"

[dependencies]
planforge-sas = { path = "../planforge-sas", version = "0.1.0" }
anyhow = "1"
tracing = "0.1"
libc = "0.2"
nom = "7"
ordered-float = "5.1.0"
itertools = "0.13"
