(define (domain adl-or-in-axiom-body)
  (:requirements :strips :derived-predicates :action-costs)
  (:predicates (a) (b) (ok))
  (:functions (cost))
  (:derived (ok) (or (a) (b)))
  (:action make-a :parameters ()
    :precondition () :effect (and (a) (increase (cost) 5)))
  (:action make-b :parameters ()
    :precondition () :effect (and (b) (increase (cost) 2))))
