(define (domain adl-exists-precondition)
  (:requirements :strips :typing :action-costs)
  (:types key)
  (:predicates (holding ?k - key) (opened))
  (:functions (cost))
  (:action grab :parameters (?k - key)
    :precondition () :effect (and (holding ?k) (increase (cost) 1)))
  (:action open-with-any :parameters ()
    :precondition (exists (?k - key) (holding ?k))
    :effect (and (opened) (increase (cost) 1)))
  (:action force-open :parameters ()
    :precondition () :effect (and (opened) (increase (cost) 9))))
