(define (domain adl-imply-compound-antecedent)
  (:requirements :strips :disjunctive-preconditions :action-costs)
  (:predicates (p) (q) (r) (gone))
  (:functions (cost))
  (:action make-r :parameters ()
    :precondition () :effect (and (r) (increase (cost) 3)))
  (:action go :parameters ()
    :precondition (imply (and (p) (q)) (r))
    :effect (and (gone) (increase (cost) 1))))
