use crate::translate::build_model as bm;
use crate::translate::normalization_function_admin::{NormalizationFunctionAdministrator, NumericAxiom};
use crate::translate::pddl_ast::{Condition, Domain, Problem};
use crate::translate::pddl_parser::SExpr;
use std::collections::{HashMap, HashSet};

const OBJECT_PREDICATE: &str = "@object";
const KW_AND: &str = "and";
const KW_FORALL: &str = "forall";
const KW_WHEN: &str = "when";
const KW_NOT: &str = "not";
const KW_INCREASE: &str = "increase";
const KW_DECREASE: &str = "decrease";
const KW_ASSIGN: &str = "assign";
const KW_SCALE_UP: &str = "scale-up";
const KW_SCALE_DOWN: &str = "scale-down";
const TOTAL_COST: &str = "total-cost";
const DEFAULT_UNIT_COST: &str = "1";
const TYPE_MARKER: &str = "-";

/// A PDDL task structure suitable for normalization.
/// This contains the parsed domain and problem in a form where conditions
/// are already converted from SExpr to Condition, and actions/axioms can be
/// mutated during the normalization process.
#[derive(Debug, Clone)]
pub struct NormalizableTask {
    /// Domain name
    pub domain_name: String,
    /// Problem name  
    pub problem_name: String,
    /// Predicate definitions from domain
    pub predicates: Vec<(String, Vec<(String, Option<String>)>)>,
    /// Function (numeric fluent) definitions from domain
    pub functions: Vec<(String, Vec<(String, Option<String>)>)>,
    /// Actions with parsed preconditions (as Condition) and raw effects (as SExpr for now)
    pub actions: Vec<TaskAction>,
    /// Axioms generated during normalization
    pub axioms: Vec<TaskAxiom>,
    /// Numeric axioms generated by the function administrator
    pub numeric_axioms: Vec<NumericAxiom>,
    /// Objects from problem
    pub objects: Vec<(String, Option<String>)>,
    /// Initial state atoms (as SExpr for now)
    pub init: Vec<SExpr>,
    /// Goal condition (parsed as Condition)
    pub goal: Condition,
    /// Optimization metric: (direction, expression)
    /// Direction is "<" for minimize, ">" for maximize
    pub metric: (String, Option<SExpr>),
    /// Counter for generating unique axiom names
    axiom_counter: usize,
    /// Function administrator for managing derived numeric functions (not Clone)
    /// Note: This field makes NormalizableTask non-Clone, but we add a custom Clone impl
    #[allow(dead_code)]
    function_administrator: NormalizationFunctionAdministrator,
}

/// Action in the normalizable task with parsed precondition
#[derive(Debug, Clone)]
pub struct TaskAction {
    pub name: String,
    pub parameters: Vec<(String, Option<String>)>,
    pub precondition: Condition,
    /// Effects as conditional effects with parsed conditions
    pub effects: Vec<TaskEffect>,
    /// Cost effect (the increase of total-cost or cost fluent)
    /// In Python, this is extracted but also kept in effects list for backward compatibility
    pub cost: Option<SExpr>,
}

/// Conditional effect with parsed condition
#[derive(Debug, Clone)]
pub struct TaskEffect {
    /// Forall parameters for the effect
    pub parameters: Vec<(String, Option<String>)>,
    /// Condition for when the effect applies
    pub condition: Condition,
    /// The actual effect (add/delete/assign) - kept as SExpr for now
    pub effect: SExpr,
}

/// Axiom in the normalizable task
#[derive(Debug, Clone)]
pub struct TaskAxiom {
    pub name: String,
    pub parameters: Vec<(String, Option<String>)>,
    pub condition: Condition,
    /// Number of external parameters (used for rule generation)
    pub num_external_parameters: usize,
}

impl NormalizableTask {
    /// Create a normalizable task from parsed Domain and Problem ASTs
    pub fn from_ast(domain: &Domain, problem: &Problem) -> Self {
        use crate::translate::pddl_ast::sexpr_to_condition;
        let actions = build_actions(domain, sexpr_to_condition);
        
        // Convert goal from SExpr to Condition
        let goal = problem
            .goal
            .as_ref()
            .map(|s| sexpr_to_condition(s))
            .unwrap_or(Condition::True);
        
        NormalizableTask {
            domain_name: domain.name.clone(),
            problem_name: problem.name.clone(),
            predicates: domain.predicates.clone(),
            functions: domain.functions.clone(),
            actions,
            axioms: vec![],
            numeric_axioms: vec![],
            objects: problem.objects.clone(),
            init: problem.init.clone(),
            goal,
            metric: problem
                .metric
                .as_ref()
                .map(|(dir, expr)| (dir.clone(), Some(expr.clone())))
                .unwrap_or_else(|| ("<".to_string(), None)),
            axiom_counter: 0,
            function_administrator: NormalizationFunctionAdministrator::new(),
        }
    }
    
    /// Parse effects from an SExpr into a list of TaskEffect structures.
    /// Handles conditional effects with forall, when, and nested structures.
    fn parse_effects(effect_sexpr: &SExpr) -> Vec<TaskEffect> {
        parse_effects_impl(effect_sexpr)
    }
    
    /// Check if an effect SExpr is a cost effect (increase total-cost only)
    /// Python only recognizes "total-cost" as a cost fluent, not "cost"
    /// (See f_expression.py:is_cost_assignment() line 257)
    fn is_cost_effect(effect: &SExpr) -> bool {
        match effect {
            SExpr::List(items) if items.len() >= 2 => {
                // Check for (increase (total-cost) ...) ONLY
                // Note: (increase (cost) ...) is NOT considered a cost effect in Python!
                is_total_cost_increase(items)
            }
            _ => false,
        }
    }
    
    /// Parse effects and extract cost effect.
    /// Like Python's parse_effects + extract_cost, the cost effect is kept in the effects list
    /// (for backward compatibility) but also returned separately.
    fn parse_effects_and_extract_cost(effect_sexpr: &SExpr) -> (Vec<TaskEffect>, Option<SExpr>) {
        let effects = Self::parse_effects(effect_sexpr);
        let cost = extract_cost_effect(&effects);
        (effects, cost)
    }
    
    /// Add a new axiom to the task and return its name
    pub fn add_axiom(&mut self, parameters: Vec<(String, Option<String>)>, condition: Condition) -> String {
        let axiom_name = format!("@axiom-{}", self.axiom_counter);
        self.axiom_counter += 1;
        
        self.axioms.push(TaskAxiom {
            name: axiom_name.clone(),
            parameters: parameters.clone(),
            condition,
            num_external_parameters: parameters.len(),
        });
        
        axiom_name
    }
    
    /// Get a type map for a given set of parameters
    /// This is used when creating axioms to track variable types
    pub fn build_type_map(parameters: &[(String, Option<String>)]) -> HashMap<String, String> {
        parameters
            .iter()
            .filter_map(|(name, typ)| typ.as_ref().map(|t| (name.clone(), t.clone())))
            .collect()
    }

    pub fn dump(&self) -> String {
        let mut out = String::new();
        out.push_str("NormalizableTask\n");
        out.push_str(&format!("  domain: {}\n", self.domain_name));
        out.push_str(&format!("  problem: {}\n", self.problem_name));
        out.push_str(&format!("  predicates: {}\n", self.predicates.len()));
        out.push_str(&format!("  functions: {}\n", self.functions.len()));
        out.push_str(&format!("  objects: {}\n", self.objects.len()));
        out.push_str(&format!("  actions: {}\n", self.actions.len()));
        out.push_str(&format!("  axioms: {}\n", self.axioms.len()));
        out.push_str(&format!("  numeric_axioms: {}\n", self.numeric_axioms.len()));
        out.push_str("\nActions:\n");
        for action in &self.actions {
            out.push_str(&format!("  - {}{}\n", action.name, fmt_params(&action.parameters)));
            out.push_str(&format!("    pre: {}\n", fmt_condition(&action.precondition)));
            if let Some(cost) = &action.cost {
                out.push_str(&format!("    cost: {}\n", fmt_sexpr(cost)));
            }
            out.push_str(&format!("    effects: {}\n", action.effects.len()));
            for eff in &action.effects {
                out.push_str(&format!("      - params: {}\n", fmt_params(&eff.parameters)));
                out.push_str(&format!("        when: {}\n", fmt_condition(&eff.condition)));
                out.push_str(&format!("        effect: {}\n", fmt_sexpr(&eff.effect)));
            }
        }
        out.push_str("\nAxioms:\n");
        for axiom in &self.axioms {
            out.push_str(&format!(
                "  - {}{} : {} (external={})\n",
                axiom.name,
                fmt_params(&axiom.parameters),
                fmt_condition(&axiom.condition),
                axiom.num_external_parameters
            ));
        }
        out.push_str("\nGoal:\n  ");
        out.push_str(&fmt_condition(&self.goal));
        out.push('\n');
        out.push_str("\nMetric:\n  ");
        if let Some(expr) = &self.metric.1 {
            out.push_str(&format!("{} {}", self.metric.0, fmt_sexpr(expr)));
        } else {
            out.push_str(&format!("{} none", self.metric.0));
        }
        out.push('\n');
        out
    }
}

fn fmt_params(params: &[(String, Option<String>)]) -> String {
    if params.is_empty() {
        return "".to_string();
    }
    let parts: Vec<String> = params
        .iter()
        .map(|(name, typ)| match typ {
            Some(t) => format!("{} - {}", name, t),
            None => name.clone(),
        })
        .collect();
    format!("({})", parts.join(" "))
}

fn fmt_condition(cond: &Condition) -> String {
    match cond {
        Condition::Atom(name, args) => {
            if args.is_empty() {
                name.clone()
            } else {
                format!("({} {})", name, args.join(" "))
            }
        }
        Condition::Not(inner) => format!("(not {})", fmt_condition(inner)),
        Condition::And(parts) => format!(
            "(and {})",
            parts.iter().map(fmt_condition).collect::<Vec<_>>().join(" ")
        ),
        Condition::Or(parts) => format!(
            "(or {})",
            parts.iter().map(fmt_condition).collect::<Vec<_>>().join(" ")
        ),
        Condition::Forall(params, inner) => {
            format!("(forall {} {})", fmt_params(params), fmt_condition(inner))
        }
        Condition::Exists(params, inner) => {
            format!("(exists {} {})", fmt_params(params), fmt_condition(inner))
        }
        Condition::Comparison(op, left, right) => {
            format!("({} {} {})", op, fmt_sexpr(left), fmt_sexpr(right))
        }
        Condition::True => "true".to_string(),
    }
}

fn fmt_sexpr(expr: &SExpr) -> String {
    match expr {
        SExpr::Atom(a) => a.clone(),
        SExpr::List(items) => format!(
            "({})",
            items.iter().map(fmt_sexpr).collect::<Vec<_>>().join(" ")
        ),
    }
}

fn build_actions(
    domain: &Domain,
    sexpr_to_condition: impl Fn(&SExpr) -> Condition,
) -> Vec<TaskAction> {
    domain
        .actions
        .iter()
        .map(|action| {
            let precondition = action
                .precond
                .as_ref()
                .map(|s| sexpr_to_condition(s))
                .unwrap_or(Condition::True);
            let (mut effects, mut cost) = if let Some(effect_sexpr) = &action.effect {
                NormalizableTask::parse_effects_and_extract_cost(effect_sexpr)
            } else {
                (vec![], None)
            };
            if cost.is_none() && !effects.is_empty() {
                let artificial_cost = build_default_cost_effect();
                effects.push(TaskEffect {
                    parameters: vec![],
                    condition: Condition::True,
                    effect: artificial_cost.clone(),
                });
                cost = Some(artificial_cost);
            }
            TaskAction {
                name: action.name.clone(),
                parameters: action.parameters.clone(),
                precondition,
                effects,
                cost,
            }
        })
        .collect()
}

fn build_default_cost_effect() -> SExpr {
    SExpr::List(vec![
        SExpr::Atom(KW_INCREASE.to_string()),
        SExpr::List(vec![SExpr::Atom(TOTAL_COST.to_string())]),
        SExpr::Atom(DEFAULT_UNIT_COST.to_string()),
    ])
}

fn parse_effects_impl(effect_sexpr: &SExpr) -> Vec<TaskEffect> {
    use crate::translate::pddl_ast::sexpr_to_condition;
    match effect_sexpr {
        SExpr::List(items) if !items.is_empty() => parse_effect_list(items, &sexpr_to_condition),
        _ => vec![TaskEffect {
            parameters: vec![],
            condition: Condition::True,
            effect: effect_sexpr.clone(),
        }],
    }
}

fn parse_effect_list(
    items: &[SExpr],
    sexpr_to_condition: &impl Fn(&SExpr) -> Condition,
) -> Vec<TaskEffect> {
    let keyword = match &items[0] {
        SExpr::Atom(k) => k.to_lowercase(),
        _ => {
            return vec![TaskEffect {
                parameters: vec![],
                condition: Condition::True,
                effect: SExpr::List(items.to_vec()),
            }]
        }
    };
    match keyword.as_str() {
        KW_AND => items[1..]
            .iter()
            .flat_map(parse_effects_impl)
            .collect(),
        KW_FORALL => parse_forall_effect(items),
        KW_WHEN => parse_when_effect(items, sexpr_to_condition),
        _ => vec![TaskEffect {
            parameters: vec![],
            condition: Condition::True,
            effect: SExpr::List(items.to_vec()),
        }],
    }
}

fn parse_forall_effect(items: &[SExpr]) -> Vec<TaskEffect> {
    if items.len() < 3 {
        return vec![];
    }
    let params = parse_params(&items[1]);
    let inner_effects = parse_effects_impl(&items[2]);
    inner_effects
        .into_iter()
        .map(|mut eff| {
            eff.parameters.extend(params.clone());
            eff
        })
        .collect()
}

fn parse_when_effect(
    items: &[SExpr],
    sexpr_to_condition: &impl Fn(&SExpr) -> Condition,
) -> Vec<TaskEffect> {
    if items.len() < 3 {
        return vec![];
    }
    let cond = sexpr_to_condition(&items[1]);
    let inner_effects = parse_effects_impl(&items[2]);
    inner_effects
        .into_iter()
        .map(|mut eff| {
            eff.condition = if matches!(eff.condition, Condition::True) {
                cond.clone()
            } else {
                Condition::And(vec![cond.clone(), eff.condition.clone()])
            };
            eff
        })
        .collect()
}

fn parse_params(params_sexpr: &SExpr) -> Vec<(String, Option<String>)> {
    match params_sexpr {
        SExpr::List(items) => {
            let mut result = vec![];
            let mut i = 0;
            let mut pending_names = vec![];
            while i < items.len() {
                if let SExpr::Atom(atom) = &items[i] {
                    if atom == TYPE_MARKER {
                        if i + 1 < items.len() {
                            if let SExpr::Atom(type_name) = &items[i + 1] {
                                for name in pending_names.drain(..) {
                                    result.push((name, Some(type_name.clone())));
                                }
                                i += 2;
                                continue;
                            }
                        }
                    } else {
                        pending_names.push(atom.clone());
                    }
                }
                i += 1;
            }
            for name in pending_names {
                result.push((name, None));
            }
            result
        }
        _ => vec![],
    }
}

fn is_total_cost_increase(items: &[SExpr]) -> bool {
    if let Some(SExpr::Atom(op)) = items.get(0) {
        if op == KW_INCREASE {
            if let Some(SExpr::List(fluent_items)) = items.get(1) {
                if let Some(SExpr::Atom(fluent_name)) = fluent_items.get(0) {
                    return fluent_name == TOTAL_COST;
                }
            } else if let Some(SExpr::Atom(fluent_name)) = items.get(1) {
                return fluent_name == TOTAL_COST;
            }
        }
    }
    false
}

fn extract_cost_effect(effects: &[TaskEffect]) -> Option<SExpr> {
    effects
        .iter()
        .find(|eff| NormalizableTask::is_cost_effect(&eff.effect))
        .map(|eff| eff.effect.clone())
}

#[derive(Default, Debug, PartialEq)]
pub struct NormalizationOutcome {
    pub new_facts: Vec<bm::Atom>,
    pub object_predicate_required: bool,
}

fn collect_condition_vars(rule: &bm::RuleSpec) -> HashSet<String> {
    let mut vars = HashSet::new();
    for cond in &rule.conditions {
        for arg in &cond.args {
            if arg.starts_with('?') {
                vars.insert(arg.clone());
            }
        }
    }
    vars
}

/// Adds `@object(?x)` conditions for variables that only occur in the rule head.
fn remove_free_effect_variables(rules: &mut [bm::RuleSpec]) -> bool {
    let mut inserted = false;
    for rule in rules.iter_mut() {
        let mut bound_vars = collect_condition_vars(rule);
        let mut extra_conditions: Vec<bm::SymAtom> = Vec::new();
        for arg in &rule.effect.args {
            if !arg.starts_with('?') {
                continue;
            }
            if bound_vars.contains(arg) {
                continue;
            }
            let already_present = rule
                .conditions
                .iter()
                .any(|c| c.predicate == OBJECT_PREDICATE && c.args.len() == 1 && &c.args[0] == arg);
            if !already_present {
                extra_conditions.push(bm::SymAtom::new(
                    OBJECT_PREDICATE.to_string(),
                    vec![arg.clone()],
                ));
            }
            bound_vars.insert(arg.clone());
        }
        if !extra_conditions.is_empty() {
            rule.conditions.extend(extra_conditions);
            inserted = true;
        }
    }
    inserted
}

/// Deduplicates identical conditions within each rule to keep the join queue small.
fn split_duplicate_arguments(rules: &mut [bm::RuleSpec]) {
    fn rename_duplicates_in_atom(
        atom: &bm::SymAtom,
        extra_conditions: &mut Vec<bm::SymAtom>,
    ) -> bm::SymAtom {
        let mut used: HashSet<String> = HashSet::new();
        let mut new_args = atom.args.clone();
        for (idx, arg) in atom.args.iter().enumerate() {
            if !arg.starts_with('?') {
                continue;
            }
            if used.contains(arg) {
                let new_var = format!("{}@{}", arg, extra_conditions.len());
                new_args[idx] = new_var.clone();
                extra_conditions.push(bm::SymAtom::new(
                    "=".to_string(),
                    vec![arg.clone(), new_var],
                ));
            } else {
                used.insert(arg.clone());
            }
        }
        bm::SymAtom::new(atom.predicate.clone(), new_args)
    }

    for rule in rules.iter_mut() {
        let mut extra_conditions: Vec<bm::SymAtom> = Vec::new();
        rule.effect = rename_duplicates_in_atom(&rule.effect, &mut extra_conditions);
        let old_conditions = std::mem::take(&mut rule.conditions);
        let mut new_conditions: Vec<bm::SymAtom> = old_conditions
            .iter()
            .map(|cond| rename_duplicates_in_atom(cond, &mut extra_conditions))
            .collect();
        new_conditions.extend(extra_conditions);
        let mut seen: HashSet<(String, Vec<String>)> = HashSet::new();
        new_conditions.retain(|cond| {
            let key = (cond.predicate.clone(), cond.args.clone());
            seen.insert(key)
        });
        rule.conditions = new_conditions;
    }
}

/// Converts rules without conditions (and constant heads) into base facts.
fn convert_trivial_rules(rules: &mut Vec<bm::RuleSpec>) -> Vec<bm::Atom> {
    let mut produced: Vec<bm::Atom> = Vec::new();
    rules.retain(|rule| {
        if rule.conditions.is_empty() {
            if rule.effect.args.iter().any(|a| a.starts_with('?')) {
                // Unable to convert – keep the rule around for later processing.
                true
            } else {
                produced.push(bm::Atom {
                    predicate: rule.effect.predicate.clone(),
                    args: rule
                        .effect
                        .args
                        .iter()
                        .map(|a| bm::Arg::Const(a.clone()))
                        .collect(),
                });
                false
            }
        } else {
            true
        }
    });
    produced
}

/// Get predicates that can change during plan execution (fluent predicates).
/// 
/// A predicate is fluent if it appears in:
/// - Action effects (add or delete)
/// - Axiom heads (derived predicates)
/// 
/// This mirrors Python's normalize.get_fluent_predicates().
pub fn get_fluent_predicates(task: &NormalizableTask) -> HashSet<String> {
    let mut fluent_predicates = HashSet::new();
    
    // Collect predicates from action effects
    for action in &task.actions {
        for effect in &action.effects {
            // Extract predicate from effect SExpr
            if let Some(pred) = extract_effect_predicate(&effect.effect) {
                fluent_predicates.insert(pred);
            }
        }
    }
    
    // Collect predicates from axiom heads
    for axiom in &task.axioms {
        fluent_predicates.insert(axiom.name.clone());
    }
    
    fluent_predicates
}

/// Extract the predicate name from an effect SExpr.
/// Handles: (predicate args...), (not (predicate args...)), (increase/decrease/assign ...)
fn extract_effect_predicate(effect: &SExpr) -> Option<String> {
    fn is_numeric_effect(op: &str) -> bool {
        matches!(op, KW_INCREASE | KW_DECREASE | KW_ASSIGN | KW_SCALE_UP | KW_SCALE_DOWN)
    }

    match effect {
        SExpr::List(items) if items.is_empty() => None,
        SExpr::List(items) => {
            if let SExpr::Atom(op) = &items[0] {
                match op.as_str() {
                    KW_NOT => {
                        // (not (predicate args...))
                        if items.len() >= 2 {
                            if let SExpr::List(inner) = &items[1] {
                                if !inner.is_empty() {
                                    if let SExpr::Atom(pred) = &inner[0] {
                                        return Some(pred.clone());
                                    }
                                }
                            }
                        }
                        None
                    }
                    _ if is_numeric_effect(op) => {
                        // Numeric effect: (increase (function-name args...) value)
                        // Extract the function name and return defined! predicate
                        if items.len() >= 2 {
                            if let SExpr::List(func_items) = &items[1] {
                                if !func_items.is_empty() {
                                    if let SExpr::Atom(func_name) = &func_items[0] {
                                        return Some(format!("defined!{}", func_name));
                                    }
                                }
                            }
                        }
                        None
                    }
                    _ => {
                        // Simple positive effect: (predicate args...)
                        Some(op.clone())
                    }
                }
            } else {
                None
            }
        }
        SExpr::Atom(pred) => {
            // Single atom predicate with no args
            Some(pred.clone())
        }
    }
}

pub fn normalize_rules(rules: &mut Vec<bm::RuleSpec>) -> NormalizationOutcome {
    let mut outcome = NormalizationOutcome::default();
    outcome.object_predicate_required = remove_free_effect_variables(rules);
    split_duplicate_arguments(rules);
    outcome.new_facts = convert_trivial_rules(rules);
    outcome
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::translate::pddl::PddlTask;
    use crate::translate::pddl_ast::{Domain, Problem};
    use std::path::Path;

    fn rule(effect: (&str, Vec<&str>), conds: Vec<(&str, Vec<&str>)>, rtype: &str) -> bm::RuleSpec {
        bm::RuleSpec {
            rtype: rtype.to_string(),
            effect: sym_atom(effect.0, effect.1),
            conditions: conds
                .into_iter()
                .map(|(p, args)| sym_atom(p, args))
                .collect(),
        }
    }

    fn sym_atom(pred: &str, args: Vec<&str>) -> bm::SymAtom {
        bm::SymAtom::new(
            pred.to_string(),
            args.into_iter().map(|a| a.to_string()).collect(),
        )
    }

    #[test]
    fn adds_object_condition_for_free_head_var() {
        let mut rules = vec![rule(("move", vec!["?x"]), vec![], "project")];
        let inserted = remove_free_effect_variables(&mut rules);
        assert!(inserted);
        assert_eq!(rules[0].conditions.len(), 1);
        assert_eq!(rules[0].conditions[0].predicate, OBJECT_PREDICATE);
        assert_eq!(rules[0].conditions[0].args, vec!["?x".to_string()]);
    }

    #[test]
    fn duplicate_conditions_are_removed() {
        let mut rules = vec![rule(
            ("move", vec!["?x"]),
            vec![("at", vec!["?x"]), ("at", vec!["?x"])],
            "project",
        )];
        split_duplicate_arguments(&mut rules);
        assert_eq!(rules[0].conditions.len(), 1);
    }

    #[test]
    fn trivial_constant_rule_becomes_fact() {
        let mut rules = vec![rule(("ready", vec!["a1"]), vec![], "project")];
        let facts = convert_trivial_rules(&mut rules);
        assert!(rules.is_empty());
        assert_eq!(facts.len(), 1);
        assert_eq!(facts[0].predicate, "ready");
        assert_eq!(facts[0].args, vec![bm::Arg::Const("a1".to_string())]);
    }

    #[test]
    fn normalization_pipeline_runs_steps() {
        let mut rules = vec![rule(("move", vec!["?x"]), vec![], "project")];
        let outcome = normalize_rules(&mut rules);
        assert!(outcome.object_predicate_required);
        assert!(outcome.new_facts.is_empty());
        assert_eq!(rules.len(), 1);
        assert_eq!(rules[0].conditions.len(), 1);
    }

    #[test]
    #[ignore]
    fn dump_normalized_plant_watering_task() {
        let domain_path = Path::new("misc/plant-watering/domain.pddl");
        let problem_path = Path::new("misc/plant-watering/prob_4_1_1.pddl");
        let task = PddlTask::from_files(domain_path, problem_path).expect("pddl loaded");
        let domain = Domain::from_sexprs(&task.domain_forms).expect("domain parsed");
        let problem = Problem::from_sexprs(&task.problem_forms).expect("problem parsed");

        let mut normalizable = NormalizableTask::from_ast(&domain, &problem);
        normalize(&mut normalizable).expect("normalize succeeded");

        println!("{}", normalizable.dump());
    }
}

/// Axiom generated during universal quantifier removal.
#[derive(Debug, Clone)]
pub struct NormalizationAxiom {
    pub name: String,
    pub parameters: Vec<(String, Option<String>)>, // (name, type)
    pub condition: Condition,
}

/// Action with normalized condition for use during normalization.
#[derive(Debug, Clone)]
pub struct NormalizationAction {
    pub name: String,
    pub parameters: Vec<(String, Option<String>)>, // (name, type)
    pub precondition: Condition,
    // Note: effects are not included here as they're handled separately
}

/// Conditional effect with normalized condition for use during normalization.
/// Represents "when <condition> then <effect>"
#[derive(Debug, Clone)]
pub struct ConditionalEffect {
    pub parameters: Vec<(String, Option<String>)>, // (name, type) - forall parameters
    pub condition: Condition,
    // Note: the actual effect (add/delete/assign) is not included here
    // as we only need to normalize the condition
}

/// Context for managing axioms and type maps during normalization.
#[derive(Debug, Clone)]
pub struct NormalizationContext {
    pub axioms: Vec<NormalizationAxiom>,
    axiom_counter: usize,
}

impl NormalizationContext {
    pub fn new() -> Self {
        Self {
            axioms: Vec::new(),
            axiom_counter: 0,
        }
    }

    /// Create a new axiom with the given parameters and condition.
    /// Returns the axiom name.
    pub fn add_axiom(
        &mut self,
        parameters: Vec<(String, Option<String>)>,
        condition: Condition,
    ) -> String {
        let name = format!("new-axiom@{}", self.axiom_counter);
        self.axiom_counter += 1;
        self.axioms.push(NormalizationAxiom {
            name: name.clone(),
            parameters,
            condition,
        });
        name
    }
}

/// Remove universal quantifiers from a condition.
///
/// This function implements the normalization step [1] from Python's normalize.py:
/// Replace, in a top-down fashion, <forall(vars, phi)> by <not(not-all-phi)>,
/// where <not-all-phi> is a new axiom.
///
/// The negation of forall(vars, phi) becomes exists(vars, not(phi)),
/// and we create an axiom for that existential condition.
///
/// Note: Python version includes caching of axioms by condition. For simplicity,
/// we skip caching here since Condition contains SExpr which doesn't implement Hash.
/// This may create duplicate axioms but maintains functional correctness.
pub fn remove_universal_quantifiers(
    condition: &Condition,
    type_map: &HashMap<String, String>,
    ctx: &mut NormalizationContext,
) -> Condition {
    match condition {
        Condition::Forall(_params, _inner) => {
            // Negate to get exists(params, not(inner))
            // Note: negate() recursively negates, so forall becomes exists,
            // and nested foralls also get negated
            let axiom_condition = condition.negate();

            // Collect free variables (parameters for the new axiom)
            let mut free_vars: Vec<String> = axiom_condition.free_variables().into_iter().collect();
            free_vars.sort();

            // Create typed parameters from free variables
            let typed_params: Vec<(String, Option<String>)> = free_vars
                .iter()
                .map(|v| {
                    let ty = type_map.get(v).cloned();
                    (v.clone(), ty)
                })
                .collect();

            // Recursively process the axiom condition to handle any nested foralls
            // that might appear after negation
            let processed_condition = remove_universal_quantifiers(&axiom_condition, type_map, ctx);

            // Add the axiom
            let axiom_name = ctx.add_axiom(typed_params, processed_condition);

            // Return a negated atom referencing the axiom
            Condition::Not(Box::new(Condition::Atom(axiom_name, free_vars)))
        }
        // For Exists, recursively process the inner condition
        Condition::Exists(params, inner) => {
            let processed_inner = remove_universal_quantifiers(inner, type_map, ctx);
            Condition::Exists(params.clone(), Box::new(processed_inner))
        }
        // For all other conditions, recursively process sub-parts
        _ => {
            let parts = condition.parts();
            if parts.is_empty() {
                condition.clone()
            } else {
                let new_parts: Vec<Condition> = parts
                    .iter()
                    .map(|p| remove_universal_quantifiers(p, type_map, ctx))
                    .collect();
                condition.change_parts(new_parts)
            }
        }
    }
}


/// Substitute complicated goal conditions with axioms.
///
/// This function implements the goal normalization from Python's normalize.py.
/// If the goal is:
/// - A simple literal (Atom or Not(Atom)): leave as-is
/// - A conjunction of only literals: leave as-is
/// - Otherwise: create an axiom for the goal and replace it with an atom referencing that axiom
///
/// This simplifies goal handling in the rest of the translation pipeline.
pub fn substitute_complicated_goal(
    goal: &Condition,
    ctx: &mut NormalizationContext,
) -> Condition {
    // Check if goal is a simple literal (Atom or Not(Atom))
    match goal {
        Condition::Atom(_, _) => return goal.clone(),
        Condition::Not(inner) => {
            if matches!(**inner, Condition::Atom(_, _)) {
                return goal.clone();
            }
        }
        Condition::And(parts) => {
            // Check if all parts are literals
            let all_literals = parts.iter().all(|part| match part {
                Condition::Atom(_, _) => true,
                Condition::Not(inner) => matches!(**inner, Condition::Atom(_, _)),
                _ => false,
            });
            if all_literals {
                return goal.clone();
            }
        }
        _ => {}
    }

    // Goal is complicated - create an axiom for it
    let axiom_name = ctx.add_axiom(vec![], goal.clone());
    Condition::Atom(axiom_name, vec![])
}

/// Convert condition to Disjunctive Normal Form (DNF).
///
/// This function implements the DNF transformation from Python's normalize.py.
/// After removing universal quantifiers, the following rules are applied:
/// (1) or(phi, or(psi, psi'))      ==  or(phi, psi, psi')         [Associativity]
/// (2) exists(vars, or(phi, psi))  ==  or(exists(vars, phi), exists(vars, psi)) [Distribution]
/// (3) and(phi, or(psi, psi'))     ==  or(and(phi, psi), and(phi, psi'))        [Distribution]
///
/// This pulls all disjunctions to the outermost level of the condition.
pub fn build_dnf(condition: &Condition) -> Condition {
    // Recursively process all parts first
    let processed_parts: Vec<Condition> = condition
        .parts()
        .iter()
        .map(|part| build_dnf(part))
        .collect();

    // If no parts, return as-is
    if processed_parts.is_empty() {
        return condition.clone();
    }

    // Separate disjunctive parts from other parts
    let mut disjunctive_parts: Vec<Condition> = Vec::new();
    let mut other_parts: Vec<Condition> = Vec::new();

    for part in processed_parts {
        if matches!(part, Condition::Or(_)) {
            disjunctive_parts.push(part);
        } else {
            other_parts.push(part);
        }
    }

    // If no disjunctive parts, just reconstruct with processed parts
    if disjunctive_parts.is_empty() {
        let all_parts: Vec<Condition> = condition
            .parts()
            .iter()
            .map(|part| build_dnf(part))
            .collect();
        return condition.change_parts(all_parts);
    }

    // Apply transformation rules based on the condition type
    match condition {
        // Rule (1): Associativity of disjunction
        // or(phi, or(psi, psi')) → or(phi, psi, psi')
        Condition::Or(_) => {
            let mut result_parts = other_parts;
            for part in disjunctive_parts {
                if let Condition::Or(inner_parts) = part {
                    result_parts.extend(inner_parts);
                }
            }
            Condition::Or(result_parts)
        }

        // Rule (2): Distributivity disjunction/existential quantification
        // exists(vars, or(phi, psi)) → or(exists(vars, phi), exists(vars, psi))
        Condition::Exists(params, _) => {
            if let Some(Condition::Or(or_parts)) = disjunctive_parts.first() {
                let result_parts: Vec<Condition> = or_parts
                    .iter()
                    .map(|part| Condition::Exists(params.clone(), Box::new(part.clone())))
                    .collect();
                Condition::Or(result_parts)
            } else {
                // Fallback - shouldn't happen
                condition.change_parts(
                    other_parts
                        .into_iter()
                        .chain(disjunctive_parts)
                        .collect(),
                )
            }
        }

        // Rule (3): Distributivity disjunction/conjunction
        // and(phi, or(psi, psi')) → or(and(phi, psi), and(phi, psi'))
        Condition::And(_) => {
            // Start with conjunction of non-disjunctive parts
            let mut result_parts = vec![Condition::And(other_parts.clone())];

            // Distribute each disjunctive part
            while let Some(disj) = disjunctive_parts.pop() {
                let previous_result_parts = result_parts;
                result_parts = Vec::new();

                if let Condition::Or(parts_to_distribute) = disj {
                    for part1 in &previous_result_parts {
                        for part2 in &parts_to_distribute {
                            // Create conjunction of part1 and part2
                            let new_conj = match part1 {
                                Condition::And(conj_parts) => {
                                    let mut new_parts = conj_parts.clone();
                                    new_parts.push(part2.clone());
                                    Condition::And(new_parts)
                                }
                                _ => Condition::And(vec![part1.clone(), part2.clone()]),
                            };
                            result_parts.push(new_conj);
                        }
                    }
                }
            }

            Condition::Or(result_parts)
        }

        // For other condition types, just return with processed parts
        _ => condition.change_parts(
            other_parts
                .into_iter()
                .chain(disjunctive_parts)
                .collect(),
        ),
    }
}


/// Check if a condition is a top-level disjunction.
///
/// This is used to identify conditions that should be split.
pub fn is_disjunction(condition: &Condition) -> bool {
    matches!(condition, Condition::Or(_))
}

/// Split a disjunctive condition into its parts.
///
/// This function implements the split_disjunctions step from Python's normalize.py.
/// After build_DNF, conditions are in the form or(phi, psi, ...).
/// This step splits such conditions into multiple copies, one for each disjunct.
///
/// In the Python version, this operates on a task structure with proxies that can
/// clone actions/axioms/goals. In this Rust version, we provide the building block
/// that extracts the disjunctive parts that would be used to create separate entities.
///
/// For integration with a full task structure, each part returned by this function
/// would be used to create a copy of the original action/axiom/goal.
///
/// Returns:
/// - `Some(Vec<Condition>)` - The individual disjuncts if the condition is a disjunction
/// - `None` - If the condition is not a disjunction
pub fn split_disjunction(condition: &Condition) -> Option<Vec<Condition>> {
    match condition {
        Condition::Or(parts) => Some(parts.clone()),
        _ => None,
    }
}

fn simplify_condition(condition: &Condition) -> Condition {
    match condition {
        Condition::And(parts) => {
            let mut new_parts: Vec<Condition> = parts
                .iter()
                .map(simplify_condition)
                .filter(|p| !matches!(p, Condition::True))
                .collect();
            let mut flattened = Vec::new();
            for part in new_parts.drain(..) {
                if let Condition::And(inner) = part {
                    flattened.extend(inner);
                } else {
                    flattened.push(part);
                }
            }
            match flattened.len() {
                0 => Condition::True,
                1 => flattened.into_iter().next().unwrap(),
                _ => Condition::And(flattened),
            }
        }
        Condition::Or(parts) => {
            let mut new_parts: Vec<Condition> = parts
                .iter()
                .map(simplify_condition)
                .collect();
            if new_parts.iter().any(|p| matches!(p, Condition::True)) {
                return Condition::True;
            }
            let mut flattened = Vec::new();
            for part in new_parts.drain(..) {
                if let Condition::Or(inner) = part {
                    flattened.extend(inner);
                } else {
                    flattened.push(part);
                }
            }
            match flattened.len() {
                0 => Condition::True,
                1 => flattened.into_iter().next().unwrap(),
                _ => Condition::Or(flattened),
            }
        }
        Condition::Not(inner) => Condition::Not(Box::new(simplify_condition(inner))),
        Condition::Exists(params, inner) => {
            Condition::Exists(params.clone(), Box::new(simplify_condition(inner)))
        }
        Condition::Forall(params, inner) => {
            Condition::Forall(params.clone(), Box::new(simplify_condition(inner)))
        }
        _ => condition.clone(),
    }
}

/// Move existential quantifiers out of conjunctions and group them.
///
/// This function implements the quantifier movement step from Python's normalize.py.
/// After removing universal quantifiers and creating the disjunctive form,
/// the following rules are applied:
/// (1) exists(vars, exists(vars', phi))  ==  exists(vars + vars', phi)
/// (2) and(phi, exists(vars, psi))       ==  exists(vars, and(phi, psi)),
///       if var does not occur in phi as a free variable.
///
/// This pulls existential quantifiers outward and combines them, preparing
/// for the elimination step that follows.
pub fn move_existential_quantifiers(condition: &Condition) -> Condition {
    // Recursively process all parts first
    let processed_parts: Vec<Condition> = condition
        .parts()
        .iter()
        .map(|p| move_existential_quantifiers(p))
        .collect();

    // If no parts, return as-is
    if processed_parts.is_empty() {
        return condition.clone();
    }

    // Separate existential parts from other parts
    let mut existential_parts: Vec<Condition> = Vec::new();
    let mut other_parts: Vec<Condition> = Vec::new();

    for part in processed_parts {
        if matches!(part, Condition::Exists(_, _)) {
            existential_parts.push(part);
        } else {
            other_parts.push(part);
        }
    }

    // If no existential parts, just reconstruct with processed parts
    if existential_parts.is_empty() {
        return condition.change_parts(other_parts);
    }

    // Apply transformation rules based on the condition type
    match condition {
        // Rule (1): Combine nested quantifiers
        // exists(vars, exists(vars', phi)) → exists(vars + vars', phi)
        Condition::Exists(params, _) => {
            if let Some(Condition::Exists(inner_params, inner_cond)) = existential_parts.first() {
                // Combine parameters from outer and inner exists
                let mut new_parameters = params.clone();
                new_parameters.extend(inner_params.clone());
                
                // The new condition is the inner condition's parts
                // (which should be a single condition)
                Condition::Exists(new_parameters, inner_cond.clone())
            } else {
                // No nested exists, return as-is
                condition.change_parts({
                    let mut all = other_parts;
                    all.extend(existential_parts);
                    all
                })
            }
        }

        // Rule (2): Pull quantifiers out of conjunctions
        // and(phi, exists(vars, psi)) → exists(vars, and(phi, psi))
        Condition::And(_) => {
            // Collect all parameters from existential parts
            let mut new_parameters: Vec<(String, Option<String>)> = Vec::new();
            let mut new_conjunction_parts = other_parts;
            
            for part in existential_parts {
                if let Condition::Exists(params, inner) = part {
                    new_parameters.extend(params);
                    // Extract the parts from the inner condition
                    // If it's a conjunction, add all its parts
                    // Otherwise, add the condition itself
                    match *inner {
                        Condition::And(inner_parts) => {
                            new_conjunction_parts.extend(inner_parts);
                        }
                        other => {
                            new_conjunction_parts.push(other);
                        }
                    }
                }
            }
            
            let new_conjunction = Condition::And(new_conjunction_parts);
            Condition::Exists(new_parameters, Box::new(new_conjunction))
        }

        // For other condition types, just reconstruct with processed parts
        _ => condition.change_parts({
            let mut all = other_parts;
            all.extend(existential_parts);
            all
        }),
    }
}


/// Eliminate existential quantifiers from axioms by turning them into parameters.
///
/// This function implements normalization step [5a] from Python's normalize.py.
/// After move_existential_quantifiers, axiom conditions may be in the form:
/// `exists(?x, ?y, phi)`. This step converts them to axiom parameters:
///
/// Before: axiom(a, b) with condition exists(?x, ?y, phi(?x, ?y, a, b))
/// After:  axiom(a, b, ?x, ?y) with condition phi(?x, ?y, a, b)
///
/// This is done in-place by modifying the axiom's parameters and condition.
/// The existential quantifiers are "dropped" by moving their parameters to
/// the axiom's parameter list.
pub fn eliminate_existential_quantifiers_from_axioms(
    axioms: &mut [NormalizationAxiom],
) {
    for axiom in axioms.iter_mut() {
        if let Condition::Exists(params, inner) = &axiom.condition {
            // Extend the axiom's parameters with the existential parameters
            axiom.parameters.extend(params.clone());
            
            // Replace the condition with the inner condition (first part)
            // In Python, precond.parts[0] is used, and parts is a tuple with one element
            axiom.condition = (**inner).clone();
        }
    }
}


/// Eliminate existential quantifiers from action preconditions by turning them into parameters.
///
/// This function implements normalization step [5b] from Python's normalize.py.
/// After move_existential_quantifiers, action preconditions may be in the form:
/// `exists(?x, ?y, phi)`. This step converts them to action parameters:
///
/// Before: action(a, b) with precondition exists(?x, ?y, phi(?x, ?y, a, b))
/// After:  action(a, b, ?x, ?y) with precondition phi(?x, ?y, a, b)
///
/// Note: The additional parameters don't form part of the action name - they're
/// used during grounding but not for action identification.
///
/// This is done in-place by modifying the action's parameters and precondition.
/// The existential quantifiers are "dropped" by moving their parameters to
/// the action's parameter list.
pub fn eliminate_existential_quantifiers_from_preconditions(
    actions: &mut [NormalizationAction],
) {
    for action in actions.iter_mut() {
        if let Condition::Exists(params, inner) = &action.precondition {
            // Extend the action's parameters with the existential parameters
            action.parameters.extend(params.clone());
            
            // Replace the precondition with the inner condition (first part)
            // In Python, precond.parts[0] is used, and parts is a tuple with one element
            action.precondition = (**inner).clone();
        }
    }
}


/// Eliminate existential quantifiers from conditional effect conditions.
///
/// This function implements normalization step [5c] from Python's normalize.py.
/// For effect conditions, we replace "when exists(x, phi) then e" with
/// "forall(x): when phi then e".
///
/// This is done by moving the existential parameters to the effect's parameter list.
/// The existential becomes a universal quantifier over the effect.
///
/// Before: effect with condition exists(?x, ?y, phi(?x, ?y)) and parameters []
/// After:  effect with condition phi(?x, ?y) and parameters [?x, ?y]
///
/// Note: The effect parameters represent forall quantification over the effect,
/// not existential quantification. The transformation converts the existential
/// in the condition to universal quantification over the entire conditional effect.
pub fn eliminate_existential_quantifiers_from_conditional_effects(
    effects: &mut [ConditionalEffect],
) {
    for effect in effects.iter_mut() {
        if let Condition::Exists(params, inner) = &effect.condition {
            // Extend the effect's parameters with the existential parameters
            effect.parameters.extend(params.clone());
            
            // Replace the condition with the inner condition (first part)
            effect.condition = (**inner).clone();
        }
    }
}

/// Verify and fix arithmetic expressions in the task.
///
/// This function implements verification from Python's normalize.py.
/// It validates that all function symbols used in numeric expressions are properly
/// defined in the domain. If undefined functions are found, it adds them to the
/// domain with default initialization.
///
/// From Python's normalize.py:
/// - Collects all defined function names from task.functions
/// - Recursively validates expressions in:
///   * Action effect assignments (peffect.expression)
///   * Metric expression (task.metric)
/// - For each PrimitiveNumericExpression found:
///   * If function symbol not in function_names:
///     - Print warning to stderr
///     - Add new Function with arity matching the expression
///     - For 0-arity functions: add to functions list and initialize to 0.0
///     - For higher-arity: raise error (would need parameter types)
/// - For ArithmeticExpressions: recursively verify all parts
/// - For AdditiveInverse: verify the single part
///
/// Note: This implementation works with SExpr-based effects. A full implementation
/// would require typed NumericExpression structures, but this provides basic validation
/// for function symbols found in effect expressions.
pub fn task_verify_and_fix_arithmetic_expressions(task: &mut NormalizableTask) {
    use std::collections::HashSet;
    
    // Collect all defined function names
    let mut function_names: HashSet<String> = task.functions.iter().map(|(name, _)| name.clone()).collect();
    
    // Helper to recursively scan SExpr for function symbols
    fn find_function_symbols(expr: &SExpr, symbols: &mut HashSet<String>) {
        match expr {
            SExpr::Atom(_) => {}, // Constants or variables, not functions
            SExpr::List(items) => {
                if items.is_empty() {
                    return;
                }
                // First element might be a function/operator
                if let SExpr::Atom(op) = &items[0] {
                    // Check if it looks like a function call (not a standard operator)
                    // Standard operators: +, -, *, /, =, <, >, <=, >=, etc.
                    if !matches!(op.as_str(), "+" | "-" | "*" | "/" | "=" | "<" | ">" | "<=" | ">=" | "and" | "or" | "not" | "increase" | "decrease" | "assign") {
                        // This might be a function symbol
                        symbols.insert(op.clone());
                    }
                }
                // Recursively check all sub-expressions
                for item in items {
                    find_function_symbols(item, symbols);
                }
            }
        }
    }
    
    // Collect all function symbols used in numeric effects (not predicate effects)
    let mut used_symbols = HashSet::new();
    for action in &task.actions {
        for effect in &action.effects {
            // Only check numeric effects (increase, decrease, assign)
            // Skip regular predicate effects like (at ?i ?x) or (free ?a)
            if let SExpr::List(items) = &effect.effect {
                if !items.is_empty() {
                    if let SExpr::Atom(op) = &items[0] {
                        // Only scan numeric operators
                        if matches!(op.as_str(), "increase" | "decrease" | "assign" | "scale-up" | "scale-down") {
                            find_function_symbols(&effect.effect, &mut used_symbols);
                        }
                        // Skip predicate effects (anything else)
                    }
                }
            }
        }
    }

    // Collect symbols from metric expression (if any)
    if let Some(metric_expr) = &task.metric.1 {
        find_function_symbols(metric_expr, &mut used_symbols);
    }
    
    // Check for undefined functions
    let mut undefined_functions = Vec::new();
    for symbol in &used_symbols {
        if !function_names.contains(symbol) {
            undefined_functions.push(symbol.clone());
        }
    }
    
    // Add undefined 0-arity functions with warning
    for symbol in undefined_functions {
        eprintln!(
            "WARNING: Function symbol '{}' appears in a numeric expression but is not defined in domain file.",
            symbol
        );
        eprintln!("Adding new symbol '{}' with arity 0.", symbol);
        
        // Add to functions list
        task.functions.push((symbol.clone(), vec![]));
        function_names.insert(symbol.clone());
        
        // Note: Initial value assignment would be added to task.init here
        // Format: (= (symbol) 0)
        // For now, we just add the function definition
        let init_expr = SExpr::List(vec![
            SExpr::Atom("=".to_string()),
            SExpr::List(vec![SExpr::Atom(symbol)]),
            SExpr::Atom("0".to_string()),
        ]);
        task.init.push(init_expr);
    }
}

/// Remove arithmetic expressions from the task.
///
/// This function implements normalization step [10] from Python's normalize.py.
/// It replaces complex arithmetic expressions with references to derived functions.
///
/// From Python's normalize.py:
/// ```python
/// def remove_arithmetic_expressions(task):
///     def recurse(condition):
///         if isinstance(condition, pddl.FunctionComparison):
///             parts = [task.function_administrator.get_derived_function(exp)
///                         for exp in condition.parts]
///             if condition.negated:
///                 return pddl.NegatedFunctionComparison(condition.comparator,parts)
///             else:
///                 return pddl.FunctionComparison(condition.comparator,parts)
///         else:
///             new_parts = [recurse(part) for part in condition.parts]
///             return condition.change_parts(new_parts)
///
///     # remove from conditions
///     for proxy in tuple(all_conditions(task)):
///         proxy.set(recurse(proxy.condition))
///
///     # remove from actions
///     admin = task.function_administrator
///     for act in task.actions:
///         for eff in act.effects:
///             if isinstance(eff.peffect,pddl.FunctionAssignment):
///                 assign = eff.peffect
///                 assign.expression = admin.get_derived_function(assign.expression)
///     
///     # remove from metric expression 
///     opt_dir, metric_expression = task.metric
///     if metric_expression is None:
///         assert opt_dir == '<'
///         metric_expression = -1
///     else:
///         metric_expression = admin.get_derived_function(metric_expression)
///     task.metric = (opt_dir, metric_expression)
/// ```
pub fn task_remove_arithmetic_expressions(task: &mut NormalizableTask) {
    use crate::translate::function_expression::parse_functional_expression;
    use crate::translate::normalization_function_admin::pne_to_sexpr;
    
    // Helper to process comparison conditions and replace arithmetic expressions
    fn process_condition(
        cond: &Condition,
        admin: &mut crate::translate::normalization_function_admin::NormalizationFunctionAdministrator,
    ) -> Condition {
        match cond {
            Condition::Comparison(comparator, left, right) => {
                // Parse both sides as functional expressions
                let left_result = if let Some(left_expr) = parse_functional_expression(left) {
                    // Process through function administrator
                    let pne = admin.get_derived_function(&left_expr);
                    pne_to_sexpr(&pne)
                } else {
                    // If parsing fails, keep original
                    left.clone()
                };
                
                let right_result = if let Some(right_expr) = parse_functional_expression(right) {
                    // Process through function administrator
                    let pne = admin.get_derived_function(&right_expr);
                    pne_to_sexpr(&pne)
                } else {
                    // If parsing fails, keep original
                    right.clone()
                };
                
                Condition::Comparison(comparator.clone(), left_result, right_result)
            }
            Condition::And(parts) => {
                Condition::And(parts.iter().map(|p| process_condition(p, admin)).collect())
            }
            Condition::Or(parts) => {
                Condition::Or(parts.iter().map(|p| process_condition(p, admin)).collect())
            }
            Condition::Not(inner) => {
                Condition::Not(Box::new(process_condition(inner, admin)))
            }
            Condition::Exists(params, inner) => {
                Condition::Exists(params.clone(), Box::new(process_condition(inner, admin)))
            }
            Condition::Forall(params, inner) => {
                Condition::Forall(params.clone(), Box::new(process_condition(inner, admin)))
            }
            // Atoms and True are unchanged
            _ => cond.clone(),
        }
    }
    
    // Helper to process effect expressions
    fn process_effect_expr(
        effect_sexpr: &SExpr,
        admin: &mut crate::translate::normalization_function_admin::NormalizationFunctionAdministrator,
    ) -> SExpr {
        match effect_sexpr {
            SExpr::List(items) if items.len() >= 3 => {
                // Check if this is an assignment-like effect
                if let SExpr::Atom(op) = &items[0] {
                    if matches!(op.as_str(), "assign" | "increase" | "decrease" | "scale-up" | "scale-down") {
                        // Pattern: (op fluent expression)
                        // Process the expression (items[2..])
                        let fluent = items[1].clone();
                        
                        // Build expression SExpr from remaining items
                        let expr_sexpr = if items.len() == 3 {
                            items[2].clone()
                        } else {
                            // Multiple items, wrap in a list if needed
                            items[2].clone()
                        };
                        
                        // Try to parse and process
                        let processed_expr = if let Some(func_expr) = parse_functional_expression(&expr_sexpr) {
                            let pne = admin.get_derived_function(&func_expr);
                            pne_to_sexpr(&pne)
                        } else {
                            expr_sexpr
                        };
                        
                        // Reconstruct effect
                        return SExpr::List(vec![
                            SExpr::Atom(op.clone()),
                            fluent,
                            processed_expr,
                        ]);
                    }
                }
                effect_sexpr.clone()
            }
            _ => effect_sexpr.clone(),
        }
    }
    
    // Process all action preconditions
    for i in 0..task.actions.len() {
        let precond = task.actions[i].precondition.clone();
        task.actions[i].precondition = process_condition(&precond, &mut task.function_administrator);
    }
    
    // Process all effect conditions
    for i in 0..task.actions.len() {
        for j in 0..task.actions[i].effects.len() {
            let cond = task.actions[i].effects[j].condition.clone();
            task.actions[i].effects[j].condition = process_condition(&cond, &mut task.function_administrator);
            
            // Also process the effect expression itself
            let effect_expr = task.actions[i].effects[j].effect.clone();
            task.actions[i].effects[j].effect = process_effect_expr(&effect_expr, &mut task.function_administrator);
        }
    }
    
    // Process all axiom conditions
    for i in 0..task.axioms.len() {
        let cond = task.axioms[i].condition.clone();
        task.axioms[i].condition = process_condition(&cond, &mut task.function_administrator);
    }
    
    // Process goal
    let goal = task.goal.clone();
    task.goal = process_condition(&goal, &mut task.function_administrator);
    
    // Collect all generated numeric axioms
    let numeric_axioms = task.function_administrator.get_all_axioms();
    task.numeric_axioms = numeric_axioms;
    
    // Process metric expression
    let metric_expr = task.metric.1.clone();
    let new_metric_expr = if let Some(expr) = metric_expr {
        if let Some(func_expr) = parse_functional_expression(&expr) {
            let pne = task.function_administrator.get_derived_function(&func_expr);
            Some(pne_to_sexpr(&pne))
        } else {
            Some(expr)
        }
    } else {
        Some(SExpr::Atom("-1".to_string()))
    };
    task.metric.1 = new_metric_expr;
}

/// Verify that derived predicates are not used in :init or action effects.
///
/// This function implements normalization step [11] from Python's normalize.py.
/// It validates that axiom predicates (derived predicates) do not appear in:
/// - The initial state (:init)
/// - Action effects
///
/// Derived predicates should only appear in axiom heads and in conditions.
/// If a derived predicate appears in :init or effects, the task is invalid.
///
/// From Python's normalize.py:
/// ```python
/// def verify_axiom_predicates(task):
///     axiom_names = set()
///     for axiom in task.axioms:
///         axiom_names.add(axiom.name)
///
///     for fact in task.init:
///         if getattr(fact, "predicate", None) in axiom_names:
///             raise SystemExit("error: derived predicate %r appears in :init fact '%s'" %
///                 (fact.predicate, fact))
///
///     for action in task.actions:
///         for effect in action.effects:
///             if isinstance(effect.peffect, pddl.Literal) and effect.peffect.predicate in axiom_names:
///                 raise SystemExit("error: derived predicate %r appears in effect of action %r" %
///                     (effect.peffect.predicate, action.name))
/// ```
pub fn task_verify_axiom_predicates(task: &NormalizableTask) -> Result<(), String> {
    use std::collections::HashSet;
    
    // Collect all axiom predicate names
    let axiom_names: HashSet<String> = task.axioms.iter().map(|ax| ax.name.clone()).collect();
    
    // Check that derived predicates don't appear in :init
    for init_fact in &task.init {
        // Extract predicate name from init fact
        // Init facts can be atoms like (at robot loc1) or assignments like (= (fuel) 10)
        if let Some(predicate) = extract_predicate_from_sexpr(init_fact) {
            if axiom_names.contains(&predicate) {
                return Err(format!(
                    "error: derived predicate '{}' appears in :init fact '{:?}'",
                    predicate, init_fact
                ));
            }
        }
    }
    
    // Check that derived predicates don't appear in action effects
    for action in &task.actions {
        for effect in &action.effects {
            // Extract predicate from effect
            // Effects can be atoms, negated atoms, or assignments
            if let Some(predicate) = extract_predicate_from_sexpr(&effect.effect) {
                if axiom_names.contains(&predicate) {
                    return Err(format!(
                        "error: derived predicate '{}' appears in effect of action '{}'",
                        predicate, action.name
                    ));
                }
            }
        }
    }
    
    Ok(())
}

/// Helper function to extract predicate name from an SExpr.
///
/// Handles various forms:
/// - (at robot loc1) -> "at"
/// - (not (clear block)) -> "clear"
/// - (= (fuel) 10) -> None (assignment, not a predicate)
fn extract_predicate_from_sexpr(expr: &SExpr) -> Option<String> {
    match expr {
        SExpr::Atom(_) => None,
        SExpr::List(items) => {
            if items.is_empty() {
                return None;
            }
            
            // Check first element
            match &items[0] {
                SExpr::Atom(op) => {
                    match op.as_str() {
                        // Negation: (not <atom>)
                        "not" => {
                            if items.len() >= 2 {
                                extract_predicate_from_sexpr(&items[1])
                            } else {
                                None
                            }
                        }
                        // Assignment operators: (= ...), (assign ...), etc.
                        "=" | "assign" | "increase" | "decrease" | "scale-up" | "scale-down" => None,
                        // Regular predicate
                        _ => Some(op.clone()),
                    }
                }
                _ => None,
            }
        }
    }
}

/// Placeholder for the old standalone function (kept for compatibility)
#[allow(dead_code)]
pub fn verify_and_fix_arithmetic_expressions_placeholder() {
    // This is now replaced by task_verify_and_fix_arithmetic_expressions
    unimplemented!("Use task_verify_and_fix_arithmetic_expressions instead")
}

// ============================================================================
// Task-based normalization functions
// ============================================================================
//
// These functions operate on NormalizableTask and implement the full
// normalization pipeline from Python's normalize.py

/// Remove universal quantifiers from all conditions in the task.
///
/// This implements step [1] of normalization: for each action precondition,
/// axiom condition, effect condition, and the goal, replace forall quantifiers
/// with axioms.
pub fn task_remove_universal_quantifiers(task: &mut NormalizableTask) {
    let mut axiom_cache: HashMap<String, String> = HashMap::new();
    // Process action preconditions
    for i in 0..task.actions.len() {
        if task.actions[i].precondition.has_universal_part() {
            let type_map = NormalizableTask::build_type_map(&task.actions[i].parameters);
            let condition = task.actions[i].precondition.clone();
            let new_condition = remove_universal_quantifiers_impl(
                &condition,
                &type_map,
                task,
                &mut axiom_cache,
            );
            task.actions[i].precondition = new_condition;
        }
    }
    
    // Process axiom conditions
    let mut i = 0;
    while i < task.axioms.len() {
        if task.axioms[i].condition.has_universal_part() {
            let type_map = NormalizableTask::build_type_map(&task.axioms[i].parameters);
            let condition = task.axioms[i].condition.clone();
            let new_condition = remove_universal_quantifiers_impl(
                &condition,
                &type_map,
                task,
                &mut axiom_cache,
            );
            task.axioms[i].condition = new_condition;
        }
        i += 1;
    }
    
    // Process effect conditions
    for i in 0..task.actions.len() {
        for j in 0..task.actions[i].effects.len() {
            if task.actions[i].effects[j].condition.has_universal_part() {
                let mut combined_params = task.actions[i].parameters.clone();
                combined_params.extend(task.actions[i].effects[j].parameters.clone());
                let type_map = NormalizableTask::build_type_map(&combined_params);
                let condition = task.actions[i].effects[j].condition.clone();
                let new_condition = remove_universal_quantifiers_impl(
                    &condition,
                    &type_map,
                    task,
                    &mut axiom_cache,
                );
                task.actions[i].effects[j].condition = new_condition;
            }
        }
    }
    
    // Process goal
    if task.goal.has_universal_part() {
        let type_map = HashMap::new(); // Goal has no parameters typically
        let goal = task.goal.clone();
        task.goal = remove_universal_quantifiers_impl(&goal, &type_map, task, &mut axiom_cache);
    }
}

/// Helper function for remove_universal_quantifiers that recursively processes a condition
fn remove_universal_quantifiers_impl(
    condition: &Condition,
    type_map: &HashMap<String, String>,
    task: &mut NormalizableTask,
    axiom_cache: &mut HashMap<String, String>,
) -> Condition {
    match condition {
        Condition::Forall(_params, inner) => {
            // Create axiom for negation of the forall
            let axiom_condition = condition.negate();
            let cache_key = condition_key(&axiom_condition);
            if let Some(existing_name) = axiom_cache.get(&cache_key) {
                let mut free_vars: Vec<_> = axiom_condition.free_variables().into_iter().collect();
                free_vars.sort();
                return Condition::Not(Box::new(Condition::Atom(existing_name.clone(), free_vars)));
            }
            let free_vars: Vec<_> = axiom_condition.free_variables().into_iter().collect();
            let mut axiom_params: Vec<(String, Option<String>)> = free_vars
                .iter()
                .map(|v| (v.clone(), type_map.get(v).cloned()))
                .collect();
            axiom_params.sort_by(|a, b| a.0.cmp(&b.0));

            let axiom_name = task.add_axiom(axiom_params.clone(), axiom_condition.clone());
            axiom_cache.insert(cache_key, axiom_name.clone());
            let axiom_args: Vec<String> = axiom_params.iter().map(|(n, _)| n.clone()).collect();
            Condition::Not(Box::new(Condition::Atom(axiom_name, axiom_args)))
        }
        Condition::Not(c) => {
            Condition::Not(Box::new(remove_universal_quantifiers_impl(
                c,
                type_map,
                task,
                axiom_cache,
            )))
        }
        Condition::And(parts) => {
            let new_parts: Vec<_> = parts
                .iter()
                .map(|p| remove_universal_quantifiers_impl(p, type_map, task, axiom_cache))
                .collect();
            Condition::And(new_parts)
        }
        Condition::Or(parts) => {
            let new_parts: Vec<_> = parts
                .iter()
                .map(|p| remove_universal_quantifiers_impl(p, type_map, task, axiom_cache))
                .collect();
            Condition::Or(new_parts)
        }
        Condition::Exists(params, c) => {
            let new_inner = remove_universal_quantifiers_impl(c, type_map, task, axiom_cache);
            Condition::Exists(params.clone(), Box::new(new_inner))
        }
        _ => condition.clone(),
    }
}

fn condition_key(condition: &Condition) -> String {
    match condition {
        Condition::Atom(name, args) => format!("atom({} {})", name, args.join(" ")),
        Condition::Not(inner) => format!("not({})", condition_key(inner)),
        Condition::And(parts) => {
            let parts_key: Vec<String> = parts.iter().map(condition_key).collect();
            format!("and({})", parts_key.join(","))
        }
        Condition::Or(parts) => {
            let parts_key: Vec<String> = parts.iter().map(condition_key).collect();
            format!("or({})", parts_key.join(","))
        }
        Condition::Forall(params, inner) => {
            let params_key: Vec<String> = params
                .iter()
                .map(|(n, t)| format!("{}:{}", n, t.clone().unwrap_or_default()))
                .collect();
            format!("forall({}){}", params_key.join(","), condition_key(inner))
        }
        Condition::Exists(params, inner) => {
            let params_key: Vec<String> = params
                .iter()
                .map(|(n, t)| format!("{}:{}", n, t.clone().unwrap_or_default()))
                .collect();
            format!("exists({}){}", params_key.join(","), condition_key(inner))
        }
        Condition::Comparison(op, left, right) => {
            format!("cmp({} {} {})", op, sexpr_key(left), sexpr_key(right))
        }
        Condition::True => "true".to_string(),
    }
}

fn sexpr_key(sexpr: &SExpr) -> String {
    match sexpr {
        SExpr::Atom(a) => a.clone(),
        SExpr::List(items) => {
            let parts: Vec<String> = items.iter().map(sexpr_key).collect();
            format!("({})", parts.join(" "))
        }
    }
}

/// Substitute complicated goal with an axiom reference.
///
/// This implements step [2] of normalization for the goal specifically.
pub fn task_substitute_complicated_goal(task: &mut NormalizableTask) {
    let goal = task.goal.clone();
    task.goal = substitute_complicated_goal_impl(&goal, task);
}

/// Helper that can add axioms to task
fn substitute_complicated_goal_impl(goal: &Condition, task: &mut NormalizableTask) -> Condition {
    // Check if goal is a simple literal or conjunction of literals
    match goal {
        Condition::Atom(_, _) => return goal.clone(),
        Condition::Not(inner) => {
            if matches!(**inner, Condition::Atom(_, _)) {
                return goal.clone();
            }
        }
        Condition::And(parts) => {
            let all_literals = parts.iter().all(|p| match p {
                Condition::Atom(_, _) => true,
                Condition::Not(inner) => matches!(**inner, Condition::Atom(_, _)),
                _ => false,
            });
            if all_literals {
                return goal.clone();
            }
        }
        _ => {}
    }
    
    // Goal is complicated - create axiom
    let axiom_name = task.add_axiom(vec![], goal.clone());
    Condition::Atom(axiom_name, vec![])
}

/// Convert all conditions in the task to DNF.
///
/// This implements step [3] of normalization.
pub fn task_build_dnf(task: &mut NormalizableTask) {
    // Process action preconditions
    for action in task.actions.iter_mut() {
        if action.precondition.has_disjunction() {
            action.precondition = simplify_condition(&build_dnf(&action.precondition));
        }
    }
    
    // Process axiom conditions
    for axiom in task.axioms.iter_mut() {
        if axiom.condition.has_disjunction() {
            axiom.condition = simplify_condition(&build_dnf(&axiom.condition));
        }
    }
    
    // Process effect conditions
    for action in task.actions.iter_mut() {
        for effect in action.effects.iter_mut() {
            if effect.condition.has_disjunction() {
                effect.condition = simplify_condition(&build_dnf(&effect.condition));
            }
        }
    }
    
    // Process goal
    if task.goal.has_disjunction() {
        task.goal = simplify_condition(&build_dnf(&task.goal));
    }
}

/// Split disjunctions in the task, creating multiple copies of actions/axioms.
///
/// This implements step [4] of normalization.
pub fn task_split_disjunctions(task: &mut NormalizableTask) {
    // Split action preconditions
    let mut new_actions = Vec::new();
    let mut actions_to_remove = Vec::new();
    
    for (idx, action) in task.actions.iter().enumerate() {
        if let Some(parts) = split_disjunction(&action.precondition) {
            // Create a copy of the action for each disjunct
            for part in parts {
                let mut new_action = action.clone();
                new_action.precondition = part;
                new_actions.push(new_action);
            }
            actions_to_remove.push(idx);
        }
    }
    
    // Remove original actions (in reverse order to maintain indices)
    for idx in actions_to_remove.iter().rev() {
        task.actions.remove(*idx);
    }
    task.actions.extend(new_actions);
    
    // Split axiom conditions
    let mut new_axioms = Vec::new();
    let mut axioms_to_remove = Vec::new();
    
    for (idx, axiom) in task.axioms.iter().enumerate() {
        if let Some(parts) = split_disjunction(&axiom.condition) {
            for part in parts {
                let mut new_axiom = axiom.clone();
                new_axiom.condition = part;
                new_axioms.push(new_axiom);
            }
            axioms_to_remove.push(idx);
        }
    }
    
    for idx in axioms_to_remove.iter().rev() {
        task.axioms.remove(*idx);
    }
    task.axioms.extend(new_axioms);

    // Split conditional effect conditions
    for action in task.actions.iter_mut() {
        let mut new_effects = Vec::new();
        for effect in action.effects.iter() {
            if let Some(parts) = split_disjunction(&effect.condition) {
                for part in parts {
                    let mut new_effect = effect.clone();
                    new_effect.condition = part;
                    new_effects.push(new_effect);
                }
            } else {
                new_effects.push(effect.clone());
            }
        }
        action.effects = new_effects;
    }
    
    // Note: Goal disjunctions should have been converted to axioms in substitute_complicated_goal
}

/// Move existential quantifiers in all conditions.
///
/// This implements step [5] of normalization.
pub fn task_move_existential_quantifiers(task: &mut NormalizableTask) {
    // Process action preconditions
    for action in task.actions.iter_mut() {
        if action.precondition.has_existential_part() {
            action.precondition = move_existential_quantifiers(&action.precondition);
        }
    }
    
    // Process axiom conditions
    for axiom in task.axioms.iter_mut() {
        if axiom.condition.has_existential_part() {
            axiom.condition = move_existential_quantifiers(&axiom.condition);
        }
    }
    
    // Process effect conditions
    for action in task.actions.iter_mut() {
        for effect in action.effects.iter_mut() {
            if effect.condition.has_existential_part() {
                effect.condition = move_existential_quantifiers(&effect.condition);
            }
        }
    }
    
    // Process goal
    if task.goal.has_existential_part() {
        task.goal = move_existential_quantifiers(&task.goal);
    }
}

/// Eliminate existential quantifiers from axioms (step 5a).
pub fn task_eliminate_existential_quantifiers_from_axioms(task: &mut NormalizableTask) {
    for axiom in task.axioms.iter_mut() {
        if let Condition::Exists(params, inner) = &axiom.condition {
            axiom.parameters.extend(params.clone());
            axiom.condition = (**inner).clone();
        }
    }
}

/// Eliminate existential quantifiers from action preconditions (step 5b).
pub fn task_eliminate_existential_quantifiers_from_preconditions(task: &mut NormalizableTask) {
    for action in task.actions.iter_mut() {
        if let Condition::Exists(params, inner) = &action.precondition {
            action.parameters.extend(params.clone());
            action.precondition = (**inner).clone();
        }
    }
}

/// Eliminate existential quantifiers from effect conditions (step 5c).
pub fn task_eliminate_existential_quantifiers_from_conditional_effects(task: &mut NormalizableTask) {
    for action in task.actions.iter_mut() {
        for effect in action.effects.iter_mut() {
            if let Condition::Exists(params, inner) = &effect.condition {
                effect.parameters.extend(params.clone());
                effect.condition = (**inner).clone();
            }
        }
    }
}

/// Main normalization function that applies all normalization steps.
///
/// This matches the Python normalize() function and applies the following steps:
/// 1. Remove universal quantifiers
/// 2. Substitute complicated goal
/// 3. Build DNF
/// 4. Split disjunctions
/// 5. Move existential quantifiers
/// 6. Eliminate existential quantifiers from axioms (5a)
/// 7. Eliminate existential quantifiers from preconditions (5b)
/// 8. Eliminate existential quantifiers from conditional effects (5c)
/// 9. Verify and fix arithmetic expressions
/// 10. Remove arithmetic expressions
/// 11. Verify axiom predicates
///
/// Returns an error if validation fails (e.g., derived predicates in :init or effects).
pub fn normalize(task: &mut NormalizableTask) -> Result<(), String> {
    task_remove_universal_quantifiers(task);
    task_substitute_complicated_goal(task);
    task_build_dnf(task);
    task_split_disjunctions(task);
    task_move_existential_quantifiers(task);
    task_eliminate_existential_quantifiers_from_axioms(task);
    task_eliminate_existential_quantifiers_from_preconditions(task);
    task_eliminate_existential_quantifiers_from_conditional_effects(task);
    task_verify_and_fix_arithmetic_expressions(task);
    task_remove_arithmetic_expressions(task);
    task_verify_axiom_predicates(task)?;
    Ok(())
}

/// Build exploration rules from normalized task for instantiation.
/// This converts normalized actions and axioms into datalog-style rules for model computation.
/// Mirrors Python's normalize.build_exploration_rules().
pub fn build_exploration_rules(
    task: &NormalizableTask,
) -> Result<Vec<(Vec<bm::SymAtom>, bm::SymAtom)>, String> {
    let mut rules = Vec::new();
    
    // For each action, create a rule for the precondition
    // @action-name(?params) :- precondition-atoms
    for action in &task.actions {
        let rule_head = get_action_predicate(action);
        let rule_body = condition_to_rule_body(&action.parameters, &action.precondition);
        rules.push((rule_body, rule_head));
        
        // Also create rules for effects (both unconditional and conditional)
        // effect-atom :- @action-name(?params), effect-condition
        for effect in &action.effects {
            // Get all variables: action parameters + effect forall parameters
            let mut all_params = action.parameters.clone();
            all_params.extend(effect.parameters.clone());
            
            let effect_heads = get_effect_rule_heads_checked(effect)?;
            
            if !effect_heads.is_empty() {
                let mut effect_body = vec![get_action_predicate(action)];
                // Add effect condition atoms (if not trivially true)
                if !matches!(&effect.condition, Condition::True) {
                    let cond_atoms = condition_to_rule_body(&[], &effect.condition);
                    effect_body.extend(cond_atoms);
                }
                for head in effect_heads {
                    rules.push((effect_body.clone(), head));
                }
            }
        }
    }
    
    // For each axiom, create rules
    for axiom in &task.axioms {
        // Application rule: @axiom(?params) :- axiom-condition
        let app_rule_head = get_axiom_predicate(axiom);
        let app_rule_body = condition_to_rule_body(&axiom.parameters, &axiom.condition);
        rules.push((app_rule_body, app_rule_head.clone()));
        
        // Effect rule: axiom-name(?external-params) :- @axiom(?params)
        // Python: params = axiom.parameters[:axiom.num_external_parameters]
        // For now, use all parameters (proper handling needs num_external_parameters)
        let eff_rule_head = bm::SymAtom::new(
            axiom.name.clone(),
            axiom
                .parameters
                .iter()
                .take(axiom.num_external_parameters)
                .map(|(name, _)| {
                    if name.starts_with('?') { name.clone() } else { format!("?{}", name) }
                })
                .collect(),
        );
        let eff_rule_body = vec![app_rule_head];
        rules.push((eff_rule_body, eff_rule_head));
    }
    
    // Goal reachability rule: @goal-reachable :- goal-atoms
    let goal_rule_head = bm::SymAtom::new("@goal-reachable".to_string(), vec![]);
    let goal_rule_body = condition_to_rule_body(&[], &task.goal);
    rules.push((goal_rule_body, goal_rule_head));
    
    // Add numeric axiom rules for function tracking (matches Python)
    // For each NumericAxiom from the function administrator:
    // 1. Rule: @axiom(?params) :- defined!part1(?args), defined!part2(?args), ...
    // 2. Rule: defined!axiom-head(?params) :- @axiom(?params)
    // 3. Rule: fluent-head(?params) :- @axiom(?params), fluent!part(?args)  (for fluent tracking)
    for axiom in &task.numeric_axioms {
        // Rule 1: @axiom :- defined!parts...
        // Head: atom representing the axiom application
        let axiom_pred = get_numeric_axiom_predicate(axiom);
        let mut rule_body = Vec::new();
        for part in &axiom.parts {
            if let crate::translate::function_expression::FunctionalExpression::Primitive(pne) = part {
                rule_body.push(get_defined_function_predicate(&pne.symbol, &pne.args));
            }
        }
        rules.push((rule_body.clone(), axiom_pred.clone()));
        
        // Rule 2: defined!axiom-head :- @axiom
        let head = axiom.get_head();
        let rule_2_head = get_defined_function_predicate(&head.symbol, &axiom.parameters);
        rules.push((vec![axiom_pred.clone()], rule_2_head));
        
        // Rule 3: For each primitive part, add fluent tracking rule
        // fluent-head :- @axiom, fluent!part
        let fluent_head_pred = bm::SymAtom::new(head.symbol.clone(), axiom.parameters.clone());
        for part in &axiom.parts {
            if let crate::translate::function_expression::FunctionalExpression::Primitive(pne) = part {
                let mut fluent_body = vec![axiom_pred.clone()];
                let fluent_part = bm::SymAtom::new(pne.symbol.clone(), pne.args.clone());
                fluent_body.push(fluent_part);
                rules.push((fluent_body, fluent_head_pred.clone()));
            }
        }
    }
    
    Ok(rules)
}

/// Get the axiom predicate atom for a numeric axiom
fn get_numeric_axiom_predicate(
    axiom: &crate::translate::normalization_function_admin::NumericAxiom,
) -> bm::SymAtom {
    let mut args = axiom.parameters.clone();
    for part in &axiom.parts {
        if let crate::translate::function_expression::FunctionalExpression::Primitive(pne) = part {
            args.extend(pne.args.clone());
        }
    }
    bm::SymAtom::new(axiom.name.clone(), args)
}

/// Get the action predicate atom for use in exploration rules.
/// Creates an atom like @action-move(?bot, ?from, ?to)
fn get_action_predicate(action: &TaskAction) -> bm::SymAtom {
    let predicate = format!("@action-{}", action.name);
    let args: Vec<String> = action
        .parameters
        .iter()
        .map(|(name, _type)| {
            if name.starts_with('?') {
                name.clone()
            } else {
                format!("?{}", name)
            }
        })
        .collect();
    bm::SymAtom::new(predicate, args)
}

/// Get the effect head atom for a conditional effect.
/// Returns None for negated atoms or unsupported effects.
fn get_effect_rule_heads_checked(effect: &TaskEffect) -> Result<Vec<bm::SymAtom>, String> {
    use crate::translate::pddl_parser::SExpr;

    match &effect.effect {
        SExpr::List(items) if !items.is_empty() => {
            if let SExpr::Atom(op) = &items[0] {
                if op == "not" {
                    return Ok(Vec::new());
                }
                if matches!(op.as_str(), "increase" | "decrease" | "assign" | "scale-up" | "scale-down") {
                    if items.len() >= 2 {
                        if let SExpr::List(func_items) = &items[1] {
                            if let Some(SExpr::Atom(func_name)) = func_items.get(0) {
                                let args: Vec<String> = func_items[1..]
                                    .iter()
                                    .filter_map(|item| {
                                        if let SExpr::Atom(s) = item {
                                            Some(s.clone())
                                        } else {
                                            None
                                        }
                                    })
                                    .collect();
                                return Ok(vec![
                                    get_defined_function_predicate(func_name, &args),
                                    bm::SymAtom::new(func_name.clone(), args),
                                ]);
                            }
                        }
                    }
                    return Err("numeric effect missing function head".to_string());
                }
            }

            if let SExpr::Atom(predicate) = &items[0] {
                let args: Vec<String> = items[1..]
                    .iter()
                    .filter_map(|item| {
                        if let SExpr::Atom(s) = item {
                            Some(s.clone())
                        } else {
                            None
                        }
                    })
                    .collect();
                return Ok(vec![bm::SymAtom::new(predicate.clone(), args)]);
            }
            Err("effect head is not an atom".to_string())
        }
        _ => Err("effect is not a non-empty list".to_string()),
    }
}

/// Get the axiom predicate atom for use in exploration rules.
/// Creates an atom using the axiom's name
fn get_axiom_predicate(axiom: &TaskAxiom) -> bm::SymAtom {
    let args: Vec<String> = axiom
        .parameters
        .iter()
        .map(|(name, _type)| {
            if name.starts_with('?') {
                name.clone()
            } else {
                format!("?{}", name)
            }
        })
        .collect();
    bm::SymAtom::new(axiom.name.clone(), args)
}

/// Convert a condition to a rule body (list of positive atoms).
/// Extracts parameter type predicates and positive literals from the condition.
fn condition_to_rule_body(
    parameters: &[(String, Option<String>)],
    condition: &Condition,
) -> Vec<bm::SymAtom> {
    let mut result = Vec::new();
    
    // Add type predicates for parameters
    for (param_name, param_type) in parameters {
        if let Some(type_name) = param_type {
            let param_var = if param_name.starts_with('?') {
                param_name.clone()
            } else {
                format!("?{}", param_name)
            };
            result.push(bm::SymAtom::new(type_name.clone(), vec![param_var]));
        }
    }
    
    // Extract positive literals from condition
    extract_positive_literals(condition, &mut result);
    
    result
}

/// Recursively extract positive (non-negated) literals from a condition.
fn extract_positive_literals(condition: &Condition, result: &mut Vec<bm::SymAtom>) {
    match condition {
        Condition::True => {
            // True condition adds no atoms
        }
        Condition::Atom(predicate, args) => {
            // Positive atom - add it
            result.push(bm::SymAtom::new(predicate.clone(), args.clone()));
        }
        Condition::And(conditions) => {
            // Conjunction - extract from all subconditions
            for cond in conditions {
                extract_positive_literals(cond, result);
            }
        }
        Condition::Or(_conditions) => {
            // Disjunction - after normalization, this shouldn't appear in simple preconditions
            // but if it does, we skip it (can't easily represent in datalog)
        }
        Condition::Not(cond) => {
            // Check if it's a negated atom (negative precondition)
            // In relaxed semantics, we ignore negative preconditions
            // But if it's not(not(X)), we should handle the inner part
            if let Condition::Not(inner) = cond.as_ref() {
                // Double negation - extract from inner
                extract_positive_literals(inner, result);
            }
            // Otherwise skip (negative literal)
        }
        Condition::Exists(params, cond) => {
            // Existential - add parameter types and extract from body
            for (param_name, param_type) in params {
                if let Some(type_name) = param_type {
                    let param_var = if param_name.starts_with('?') {
                        param_name.clone()
                    } else {
                        format!("?{}", param_name)
                    };
                    result.push(bm::SymAtom::new(type_name.clone(), vec![param_var]));
                }
            }
            extract_positive_literals(cond, result);
        }
        Condition::Forall(_params, _cond) => {
            // Universal quantifier - shouldn't appear after normalization
            // Skip if it does
        }
        Condition::Comparison(_op, left, right) => {
            add_defined_function_predicates_from_sexpr(left, result);
            add_defined_function_predicates_from_sexpr(right, result);
        }
    }
}

fn add_defined_function_predicates_from_sexpr(expr: &SExpr, result: &mut Vec<bm::SymAtom>) {
    use crate::translate::function_expression::parse_functional_expression;

    if let Some(func_expr) = parse_functional_expression(expr) {
        let mut primitives = Vec::new();
        collect_primitives(&func_expr, &mut primitives);
        for pne in primitives {
            result.push(get_defined_function_predicate(&pne.symbol, &pne.args));
        }
    }
}

fn collect_primitives(
    expr: &crate::translate::function_expression::FunctionalExpression,
    out: &mut Vec<crate::translate::function_expression::PrimitiveNumericExpression>,
) {
    use crate::translate::function_expression::FunctionalExpression;

    match expr {
        FunctionalExpression::Primitive(pne) => out.push(pne.clone()),
        FunctionalExpression::Arithmetic(ae) => {
            for part in &ae.parts {
                collect_primitives(part, out);
            }
        }
        FunctionalExpression::AdditiveInverse(ai) => collect_primitives(&ai.part, out),
        FunctionalExpression::Constant(_) => {}
    }
}

fn get_defined_function_predicate(symbol: &str, args: &[String]) -> bm::SymAtom {
    bm::SymAtom::new(format!("defined!{}", symbol), args.to_vec())
}
