(define (domain costfn)
  (:requirements :strips :typing :action-costs)
  (:types loc)
  (:predicates (at ?l - loc) (done))
  (:functions (total-cost) - number (travel ?a - loc ?b - loc) - number)
  (:action move :parameters (?a - loc ?b - loc)
    :precondition (at ?a)
    :effect (and (at ?b) (not (at ?a)) (increase (total-cost) (travel ?a ?b))))
  (:action finish :parameters ()
    :precondition (at l2) :effect (and (done) (increase (total-cost) 1))))
